name: test-gha
on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Initial List
        run: ls
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Py zip
        run: |
          mkdir python
          pip3 install -r requirements.txt -t python
          zip -rq python.zip python
