name: test-gha
on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Build Py zip
        run: |
          mkdir python
          pip3 install requirements.txt python
          zip -rq python.zip python
